### ISSUE TITLE
Permission Denied - multicast_snooping

### ISSUE THREAD

**Issue by vinsworldcom** [adjacentlink/python-etce#7]
Running on Docker for Windows with WSL2 integration, getting:

```
root@4177eaff57f1:/emane-sims-etce# ./start_demo.sh root 2-node/ --runtostep run --policy autoadd
sshuser=root
demodir=2-node/
Removing contents of "/tmp/etce/lxcroot" directory.
Bringing up bridge: emanenode0
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/etce/lxcmanager.py", line 58, in startlxcs
    dryrun=dryrun)
  File "/usr/lib/python3.6/site-packages/etce/lxcmanager.py", line 144, in start
    enablemulticastsnooping=True)
  File "/usr/lib/python3.6/site-packages/etce/platform.py", line 113, in bridgeup
    self._impl.bridgeup(bridgename, addifs, enablemulticastsnooping)
  File "/usr/lib/python3.6/site-packages/etce/linux/platformimpl.py", line 143, in bridgeup
    with open('/sys/devices/virtual/net/%s/bridge/multicast_snooping' % bridgename, 'w') as sf:
PermissionError: [Errno 13] Permission denied: '/sys/devices/virtual/net/emanenode0/bridge/multicast_snooping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/etce-lxc", line 109, in <module>
    main()
  File "/bin/etce-lxc", line 102, in main
    args.func(args)
  File "/usr/lib/python3.6/site-packages/etce/lxcfieldmanager.py", line 72, in startfield
    args.dryrun)
  File "/usr/lib/python3.6/site-packages/etce/lxcmanager.py", line 60, in startlxcs
    raise LXCError(e.message)
AttributeError: 'PermissionError' object has no attribute 'message'
Waiting for LXCs ...

TestCollection:
        2-node

Ignoring kill argument "both" used in conjunction with runtostep. Using "before" instead.
```

Running the same Docker container on Windows without WSL2 integration works fine.  Any idea about why the `/sys/devices/virtual/net/emanenode0/bridge/multicast_snooping` creation is denied in one flavor vs. the other?

Cheers.

**Comment by eschreiber-alink** [comment]
I don't have ready access to a WSL2 environment. Try troubleshooting the issue outside of ETCE by running the bridge creation commands manually. As root:

    # bring up the bridge
    root@host:~# ip link add emanenode0 type bridge
    root@host:~# ip link set emanenode0 up

    # check the current snooping value
    root@host:~# cat /sys/devices/virtual/net/emanenode0/bridge/multicast_snooping
    1

    # set to 0
    root@host:~# echo 0 > /sys/devices/virtual/net/emanenode0/bridge/multicast_snooping 
    root@host:~# cat /sys/devices/virtual/net/emanenode0/bridge/multicast_snooping 
    0

**Comment by vinsworldcom** [comment]
Eric,

Thanks, I realized my issue didn't include the additional commands I had captured.  The 'multicast_snooping` "object" is not created for the interface on the WSL2 linux kernel:

```
user@hostname:/mnt/c/Users/user$ sudo ip link add emanenode0 type bridge
user@hostname:/mnt/c/Users/user$ sudo ip link set emanenode0 up
user@hostname:/mnt/c/Users/user$ cat /sys/devices/virtual/net/emanenode0/bridge/multicast_snooping
cat: /sys/devices/virtual/net/emanenode0/bridge/multicast_snooping: No such file or directory
user@hostname:/mnt/c/Users/user$ ls /sys/devices/virtual/net/emanenode0/bridge/
ageing_time    group_fwd_mask     priority         topology_change_detected
bridge_id      hello_time         root_id          topology_change_timer
default_pvid   hello_timer        root_path_cost   vlan_filtering
flush          max_age            root_port        vlan_protocol
forward_delay  nf_call_arptables  stp_state        vlan_stats_enabled
gc_timer       nf_call_ip6tables  tcn_timer
group_addr     nf_call_iptables   topology_change
user@hostname:/mnt/c/Users/user$ uname -a
Linux hostname 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

If the 'multicast_snooping` "object" is not created, I wonder what is preventing that?  The WSL2 Linux in use is Ubuntu 20.04:

```
PS USER C:\Users\user> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

I changed "True" to "False" for `enablemulticastsnooping` in:

"/usr/lib/python3.6/site-packages/etce/lxcmanager.py":
```
   142                      self._platform.bridgeup(bridge.devicename,
   143                                              bridge.addifs,
   144                                              enablemulticastsnooping=False)
```

And all seems to work fine now since the "False" skips setting the `multicast_snooping` "object" later in "/usr/lib/python3.6/site-packages/etce/linux/platformimpl.py".  There doesn't seem to be an `etce-lxc` option for `multicast_snooping` on or off.

Cheers.

**Comment by vinsworldcom** [comment]
Since there seems to be no way to configure whether you want `multicast_snooping` on or off; rather it's set to `True` in "/usr/lib/python3.6/site-packages/etce/lxcmanager.py" before calling "/usr/lib/python3.6/site-packages/etce/linux/platformimpl.py", maybe a simple check in "/usr/lib/python3.6/site-packages/etce/linux/platformimpl.py" to see if it exists before operating on it:

```
diff --git a/etce/linux/platformimpl.py b/etce/linux/platformimpl.py
index 8614e41..6ba8cd4 100644
--- a/etce/linux/platformimpl.py
+++ b/etce/linux/platformimpl.py
@@ -140,8 +140,9 @@ class PlatformImpl(etce.platformimpl.PlatformImpl):
             self.runcommand('ip link set %s up' % interface)

         if enablemulticastsnooping:
-            with open('/sys/devices/virtual/net/%s/bridge/multicast_snooping' % bridgename, 'w') as sf:
-                sf.write('0')
+            if os.path.exists('/sys/devices/virtual/net/%s/bridge/multicast_snooping' % bridgename):
+                with open('/sys/devices/virtual/net/%s/bridge/multicast_snooping' % bridgename, 'w') as sf:
+                    sf.write('0')


     def bridgedown(self, bridgename, addifs):
```

Cheers.

**Comment by eschreiber-alink** [comment]
Added this check to develop branch. Thanks for your contribution.
